version: '3'
services:
  anns:
    image: "mikaellaine/anns:latest"
    ports:
     - "8888:8888"
     - "8887:8887"
     - "6006:6006"
    volumes:
     - $PWD:/home/digitalist
    #entrypoint: /bin/bash 
    command: /usr/local/bin/jupyter-notebook  --no-browser --port=8888 --ip=0.0.0.0 --allow-root --NotebookApp.token= --NotebookApp.password=


